# Generated by Django 2.1.4 on 2019-01-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100)),
                ('site_title', models.CharField(blank=True, max_length=100)),
                ('site_phone', models.CharField(blank=True, max_length=25)),
                ('site_email', models.EmailField(max_length=100, unique=True)),
                ('site_address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
