# Generated by Django 2.1.4 on 2019-01-02 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(help_text='e.g Facebook', max_length=30)),
                ('website_link', models.CharField(help_text='e.g facebook.com', max_length=50)),
                ('username', models.CharField(max_length=1000, verbose_name='Username/Email')),
                ('password', models.CharField(blank=True, max_length=1000)),
                ('key', models.CharField(blank=True, max_length=55)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
